/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadia Putri
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid_obat = new javax.swing.JTextField();
        txtnama_obat = new javax.swing.JTextField();
        txtkeluhan = new javax.swing.JTextField();
        txtefek_samping = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        cb_jenis = new javax.swing.JComboBox<>();
        cb_dosis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtno_kasir = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        btn_save = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btn_reload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Bebas", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("APOTEK MOKLET");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(350, 0, 240, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 940, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel1.setText("ID Obat");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 30, 130, 40);

        jLabel2.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel2.setText("Nama Obat");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 70, 150, 40);

        jLabel3.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel3.setText("Keluhan");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 110, 130, 40);

        jLabel4.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel4.setText("Jenis");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 150, 130, 40);

        jLabel5.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel5.setText("Kategori");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 190, 130, 40);

        jLabel6.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel6.setText("Efek Samping");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 230, 160, 40);

        jLabel7.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel7.setText("Dosis");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 270, 120, 40);

        jLabel8.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel8.setText("Harga");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 310, 120, 40);

        jLabel9.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel9.setText("Expired Date");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 390, 130, 40);

        txtid_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_obatActionPerformed(evt);
            }
        });
        jPanel3.add(txtid_obat);
        txtid_obat.setBounds(190, 30, 410, 40);

        txtnama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_obatActionPerformed(evt);
            }
        });
        jPanel3.add(txtnama_obat);
        txtnama_obat.setBounds(190, 70, 410, 40);
        jPanel3.add(txtkeluhan);
        txtkeluhan.setBounds(190, 110, 410, 40);
        jPanel3.add(txtefek_samping);
        txtefek_samping.setBounds(190, 230, 410, 40);
        jPanel3.add(txtharga);
        txtharga.setBounds(190, 310, 410, 40);

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Kategori Obat --", "Bayi (0-3 tahun)", "Balita (3-5 tahun)", "Anak (6-12 tahun)", "Remaja (12-18 tahun)", "Dewasa (18-50 tahun)", "Lansia (>50 tahun)" }));
        jPanel3.add(cb_kategori);
        cb_kategori.setBounds(190, 190, 410, 40);

        cb_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Jenis Obat --", "Sirup", "Tablet", "Kapsul", "Puyer" }));
        jPanel3.add(cb_jenis);
        cb_jenis.setBounds(190, 150, 410, 40);

        cb_dosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Dosis Pemakaian --", "1x1", "2x1", "3x1" }));
        jPanel3.add(cb_dosis);
        cb_dosis.setBounds(190, 270, 410, 40);

        jLabel10.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        jLabel10.setText("No Kasir");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 350, 130, 40);

        txtno_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_kasirActionPerformed(evt);
            }
        });
        jPanel3.add(txtno_kasir);
        txtno_kasir.setBounds(190, 350, 410, 40);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(190, 390, 410, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 70, 680, 450);

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save);
        btn_save.setBounds(770, 80, 100, 40);

        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel1.add(btn_print);
        btn_print.setBounds(770, 320, 100, 40);

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(770, 160, 100, 40);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(770, 240, 100, 40);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(770, 470, 100, 40);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Obat", "NamaObat", "Keluhan", "JenisObat", "KategoriObat", "EfekSamping", "Dosis", "Harga", "NoKasir", "ExpiredDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 530, 900, 210);

        btn_reload.setText("RELOAD");
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reload);
        btn_reload.setBounds(770, 400, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(951, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtid_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_obatActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        
        String JenisObat = "";
            if(cb_jenis.getSelectedItem().equals("Sirup")) {
                JenisObat = "Sirup";
            }else if(cb_jenis.getSelectedItem().equals("Tablet")) {
                JenisObat = "Tablet";
            }else if(cb_jenis.getSelectedItem().equals("Kapsul")) {
                JenisObat = "Kapsul";
            }else {
                JenisObat = "Puyer";
            }
        
            
               
            String KategoriObat = "";
            if(cb_kategori.getSelectedItem().equals("Bayi (0-3 tahun)")) {
                KategoriObat = "Bayi (0-3 tahun)";
            }else if(cb_kategori.getSelectedItem().equals("Balita (3-5 tahun)")) {
                KategoriObat = "Balita (3-5 tahun)";
            }else if(cb_kategori.getSelectedItem().equals("Anak (6-12 tahun)")) {
                KategoriObat = "Anak (6-12 tahun)";
            }else if(cb_kategori.getSelectedItem().equals("Remaja (12-18 tahun)")) {
                KategoriObat = "Remaja (12-18 tahun)";
            }else if(cb_kategori.getSelectedItem().equals("Dewasa (18-50 tahun)")) {
                KategoriObat = "Dewasa (18-50 tahun)";
            }else {
                KategoriObat = "Lansia (>50 tahun)";
            }
            
            String Dosis = "";
            if(cb_dosis.getSelectedItem().equals("1x1")) {
                Dosis = "1x1";
            }else if(cb_dosis.getSelectedItem().equals("2x1")) {
                Dosis = "2x1";
            }else {
                Dosis = "3x1";
            }
         
            
          if ("".equals(txtid_obat.getText()) || "".equals(txtnama_obat.getText()) ||
                "".equals(txtkeluhan.getText()) || "".equals(JenisObat) ||
                "".equals(KategoriObat) ||
                "".equals(txtefek_samping.getText()) || "".equals(Dosis) ||
                "".equals(txtharga.getText()) || "".equals(txtno_kasir.getText()) ||
                "".equals(Tanggal)) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
            
            String SQL = "INSERT INTO `tb_obat`(`ID_Obat`,`NamaObat`,`Keluhan`,`JenisObat`,`KategoriObat`,`EfekSamping`,`Dosis`,`Harga`,`NoKasir`,`ExpiredDate`) " + "VALUES('"+txtid_obat.getText()+"','"+txtnama_obat.getText()+"','"+txtkeluhan.getText()+"','"+JenisObat+"','"+KategoriObat+"','"+txtefek_samping.getText()+"','"+Dosis+"','"+txtharga.getText()+"','"+txtno_kasir.getText()+"','"+Tanggal+"')";
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }   
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txtnama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_obatActionPerformed

    private void txtno_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_kasirActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txtid_obat.setText("");
        txtnama_obat.setText("");
        txtkeluhan.setText("");
        txtefek_samping.setText("");
        txtharga.setText("");
        txtno_kasir.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Apotek Moklet");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try {
            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Can't print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int baris = Table.getSelectedRow();
        if (baris != 1) {
            String ID_Obat = Table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_obat WHERE ID_Obat = '"+ID_Obat+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                         

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Tiket Kereta Api Indonesia");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try {
            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Can't print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btn_reloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reload;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cb_dosis;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtefek_samping;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid_obat;
    private javax.swing.JTextField txtkeluhan;
    private javax.swing.JTextField txtnama_obat;
    private javax.swing.JTextField txtno_kasir;
    // End of variables declaration//GEN-END:variables

    private void selectData() 
    {
        String kolom [] = {"ID_Obat","NamaObat","Keluhan","JenisObat","KategoriObat","EfekSamping","Dosis","Harga","NoKasir","ExpiredDate"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM `tb_obat`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String ID_Obat = rs.getString(1);
                String NamaObat = rs.getString(2);
                String Keluhan = rs.getString(3);
                String JenisObat = "";
                if(rs.getString(3).equals("Sirup")){
                    JenisObat = "Sirup";
                }else if(rs.getString(3).equals("Tablet")){
                    JenisObat = "Tablet";
                }else if(rs.getString(3).equals("Kapsul")){
                    JenisObat = "Kapsul";
                }else if(rs.getString(3).equals("Puyer")){
                    JenisObat = "Puyer";
                }
                String KategoriObat = "";
                if(rs.getString(3).equals("Bayi (0-3 tahun)")){
                    KategoriObat = "Bayi (0-3 tahun)";
                }else if(rs.getString(3).equals("Balita (3-5 tahun")){
                    KategoriObat = "Balita (3-5 tahun";
                }else if(rs.getString(3).equals("Anak (6-12 tahun)")){
                    KategoriObat = "Anak (6-12 tahun)";
                }else if(rs.getString(3).equals("Remaja (12-18 tahun)")){
                    KategoriObat = "Remaja (12-18 tahun))";
                }else if(rs.getString(3).equals("Dewasa (18-50 tahun)")){
                    KategoriObat = "Dewasa (18-50 tahun)";
                }else if(rs.getString(3).equals("Lansia (>50 tahun)")){
                    KategoriObat = "Lansia (>50 tahun)";
                }
                String EfekSamping = rs.getString(4);
                String Dosis = "";
                if(rs.getString(3).equals("1x1")){
                    Dosis = "1x1";
                }else if(rs.getString(3).equals("2x1")){
                    Dosis = "2x1";
                }else if(rs.getString(3).equals("3x1")){
                    Dosis = "3x1";
                }
                String Harga = rs.getString(5);
                String NoKasir = rs.getString(6);                
                String ExpiredDate = rs.getString(7);
                
                String data[] = {ID_Obat,NamaObat,Keluhan,JenisObat,KategoriObat,EfekSamping,Dosis,Harga,NoKasir,ExpiredDate};
                dtm.addRow(data);
            }
                }catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
        Table.setModel(dtm);   
            }
    }